### ISSUE TITLE
Crash: The grid doesn't contain the item at position...

### ISSUE THREAD

**Issue by JeffZane** [fondesa/recycler-view-divider#174]
### Description
After upgrading from v3.3.0 to v3.4.0, we received a lot about the following crashes
-----------

**RecyclerViewDivider version**:
v3.4.0

**API level**:
26,27,28,29,30

**Stack trace**:
```
java.lang.IndexOutOfBoundsException: The grid doesn't contain the item at position 48.
       at com.fondesa.recyclerviewdivider.DividersAroundCellKt.lineAndCellRelativeIndexesOf(DividersAroundCellKt.java:55)
       at com.fondesa.recyclerviewdivider.DividersAroundCellKt.dividersAroundCell(DividersAroundCellKt.java:26)
       at com.fondesa.recyclerviewdivider.DividerItemDecoration.drawDividers(DividerItemDecoration.java:113)
       at com.fondesa.recyclerviewdivider.DividerItemDecoration.onDraw(DividerItemDecoration.java:103)
       at com.fondesa.recyclerviewdivider.BaseDividerItemDecoration.onDraw(BaseDividerItemDecoration.java:105)
       at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4494)
       at android.view.View.draw(View.java:21618)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1998)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at com.android.internal.policy.DecorView.draw(DecorView.java:964)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3840)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3648)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2954)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
       at android.view.Choreographer.doCallbacks(Choreographer.java:875)
       at android.view.Choreographer.doFrame(Choreographer.java:776)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by fondesa** [comment]
Few questions:
- did you use the legacy API (`RecyclerViewDivider`) or the new one when you had the version **3.3.**?
- can you provide a very simple sample in which you can reproduce the bug? Otherwise, can you explain me how to reproduce it?

**Comment by fondesa** [comment]
@JeffZane Are you perhaps using a custom `GridLayoutManager.SpanSizeLookup`? If so, can you post it here?
