### ISSUE TITLE
Failed to allocate a xxx0 byte allocation with xxx free bytes and 503MB until OOM,

### ISSUE THREAD

**Issue by wkbin** [fondesa/recycler-view-divider#271]
### Description
当recycleview adapter getItemCount 发生oom
`
class XXX : RecycleView.Adapter<VH>{
    ... 
    override fun getItemCount() = Int.MAX_VALUE
    ...
}

RecycleView.apply{
    layoutManager = LinearLayoutManager().apply{  orientation = LinearLayoutManager.HORIZONTAL   }
    adapter = XXX
    dividerBuilder()
         .asSpace()
         .size(-10, TypedValue.COMPLEX_UNIT_DIP)
         .showFirstDivider()
          .build()
          .addTo(this)
}
`

-----------

**RecyclerViewDivider version**:
3.6.0

**API level**:

**How to reproduce it**: 

**Sample code**:

**Stack trace**:

```
Paste the stack trace here.
```
Process: top.zerofun.amll, PID: 12356
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 8589934600 byte allocation with 25165824 free bytes and 503MB until OOM, target footprint 33974768, growth limit 536870912
                                                                                                    	at java.util.ArrayList.<init>(ArrayList.java:166)
                                                                                                    	at com.fondesa.recyclerviewdivider.CreateGridKt.singleSpanGrid(CreateGrid.kt:34)
                                                                                                    	at com.fondesa.recyclerviewdivider.CreateGridKt.grid(CreateGrid.kt:31)
                                                                                                    	at com.fondesa.recyclerviewdivider.DividerItemDecoration.cachedGrid(DividerItemDecoration.kt:118)
                                                                                                    	at com.fondesa.recyclerviewdivider.DividerItemDecoration.getItemOffsets(DividerItemDecoration.kt:72)
                                                                                                    	at com.fondesa.recyclerviewdivider.BaseDividerItemDecoration.getItemOffsets(BaseDividerItemDecoration.kt:111)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:5588)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:10111)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1688)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
                                                                                                    	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:466)
                                                                                                    	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:134)
                                                                                                    	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:278)
                                                                                                    	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7021)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7021)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7021)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7021)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7021)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7021)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7021)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
2022-12-09 16:06:54.211 12356-12356 AndroidRuntime          top.zerofun.amll                     E  	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:831)
                                                                                                    	at android.view.View.measure(View.java:26529)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4056)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2761)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3035)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2473)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9328)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1390)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1398)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1040)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:954)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1370)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8109)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by fondesa** [comment]
Perhaps you have disabled recycling on your RecyclerView which ends up in this error. Can you share your project here if it's possible?
In the meanwhile I'm closing this issue since it lacks the details of the adapter and the RecyclerView which are the leading problem for this error.

**Comment by wkbin** [comment]
没有禁用回收，只需要Recycle.Adapter 设置 getItemCount 位 Int.Max 就会导致oom，我只是想完成一个循环列表。如果不使用divider，一切正常

**Comment by wkbin** [comment]
> Perhaps you have disabled recycling on your RecyclerView which ends up in this error. Can you share your project here if it's possible? In the meanwhile I'm closing this issue since it lacks the details of the adapter and the RecyclerView which are the leading problem for this error.

Instead of disabling recycling, just setting the getItemCount bit Int.Max to Recycle.Adapter results in oom, I just wanted to complete a loop list. If you don't use divider, everything works
